name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.0
    - name: Install locally
      run: opam install . --deps-only --with-test
    - name: Build locally
      run: opam exec -- dune build
    - name: Run tests locally
      run: opam exec -- dune runtest
