name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
    - name: Install depext module
      run: opam install -y depext
    - name: Pin locally
      run: opam pin -y add --no-action .
    - name: Install locally
      run: opam depext -y -i gstreamer
    - name: Build locally
      run: eval $(opam env) && dune build
    - name: Run tests locally
      run: eval $(opam env) && dune runtest
